# make a docker for minecraft purpur server

version: '3.8'

services:
    minecraft_server:
            build:
                    context: .
                    dockerfile: Dockerfile
            container_name: minecraft_server
            restart: unless-stopped
            environment:
                  EULA: "true"
            ports:
                    - 25565:25565
                    - 25575:25575
                    - 8080:8080
            volumes:
                  - .server_data:/server

volumes:
    server_data: